package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.FileContentReplacer
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.replaceContent
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'FindAndReplace'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("FindAndReplace")
    name = "Find and Replace"

    vcs {
        root(RelativeId("HttpsGithubComMunishPrabhuPGradlePlayRefsHeadsMaster"))
    }

    features {
        replaceContent {
            fileRules = """
                +:api-tests/src/test/java/com/demo/e2e/SampleAPITests.java
                +:e2e-tests/src/test/java/com/demo/e2e/SampleE2ETests.java
            """.trimIndent()
            pattern = "Test Case"
            regexMode = FileContentReplacer.RegexMode.FIXED_STRINGS
            replacement = "TestCase"
        }
        pullRequests {
            vcsRootExtId = "IdeaImplementation_HttpsGithubComMunishPrabhuPGradlePlayRefsHeadsMaster"
            provider = github {
                authType = token {
                    token = "credentialsJSON:a501b077-abfa-4103-b50a-24850da66bcc"
                }
                filterTargetBranch = "+:master"
                filterAuthorRole = PullRequests.GitHubRoleFilter.MEMBER
            }
        }
    }
}))

