package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'LevitateRelease'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("LevitateRelease")) {
    params {
        remove {
            select("TEST_PHASE", "", label = "TEST_PHASE", description = "Required Test Phase", display = ParameterDisplay.PROMPT,
                    options = listOf("Comprehensive", "Sanity"))
        }
        add {
            select("env.TEST_PHASE", "", label = "TEST_PHASE", description = "Required Test Phase", display = ParameterDisplay.PROMPT,
                    options = listOf("Comprehensive", "Sanity"))
        }
    }
}
