package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'PrCheck'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("PrCheck")
    name = "PR-Check"

    vcs {
        root(RelativeId("HttpsGithubComMunishPrabhuPGradlePlayRefsHeadsMaster"))
    }

    triggers {
        vcs {
        }
    }

    features {
        pullRequests {
            vcsRootExtId = "IdeaImplementation_HttpsGithubComMunishPrabhuPGradlePlayRefsHeadsMaster"
            provider = github {
                authType = token {
                    token = "credentialsJSON:a501b077-abfa-4103-b50a-24850da66bcc"
                }
                filterTargetBranch = "refs/heads/master"
                filterAuthorRole = PullRequests.GitHubRoleFilter.MEMBER
            }
        }
    }
}))

