package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'UITests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("UITests")) {
    expectSteps {
        script {
            scriptContent = """testim --label "Licensing" --branch %BRANCH% --token "b0Q13JwYtxAQ7EecdNMLbkW4YE61DcUYkpe1oAAQCTYjwwbWYA" --project "aeHu7B27U7VgxRvjagV2" --grid "Testim-Grid" --reporters junit --report-file test-report.xml"""
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            name = "Execute UI Tests"
            clearConditions()
            scriptContent = """
                set -x
                mkdir -p "%system.teamcity.build.workingDir%/.npm-packages"
                prefix=%system.teamcity.build.workingDir%/.npm-packages
                NPM_PACKAGES="%system.teamcity.build.workingDir%/.npm-packages"
                export PATH="${'$'}PATH:${'$'}NPM_PACKAGES/bin"
                export NODE_PATH="${'$'}NODE_PATH:${'$'}NPM_PACKAGES/lib/node_modules"
                npm config set prefix %system.teamcity.build.workingDir%/.npm-packages
                npm install -g @testim/testim-cli
                set +x
                %system.teamcity.build.workingDir%/.npm-packages/bin/testim \
                  --token "b0Q13JwYtxAQ7EecdNMLbkW4YE61DcUYkpe1oAAQCTYjwwbWYA" \
                  --project "aeHu7B27U7VgxRvjagV2" \
                  --label "Licensing" \
                  --branch %BRANCH% \
                  --grid "Testim-Grid" \
                  --reporters teamcity,console \
                  --report-file ui-test-report.xml
            """.trimIndent()
        }
    }
}
