package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.DockerComposeStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.dockerCompose
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Visual'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Visual")) {
    expectSteps {
        dockerCompose {
            name = "Docker Compose"
            file = "docker-compose.yml"
            forcePull = true
        }
        gradle {
            name = "Execute Visual Tests"
            tasks = "clean test --tests com.demo.e2e.SampleVisualTests"
            buildFile = "visual/build.gradle"
        }
    }
    steps {
        update<DockerComposeStep>(0) {
            enabled = false
            clearConditions()
        }
    }
}
