package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        remove {
            select("TEST_PHASE", "", label = "TEST_PHASE", description = "Required Test Phase", display = ParameterDisplay.PROMPT,
                    options = listOf("Comprehensive", "Sanity"))
        }
    }
}
