package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComMunishPrabhuPGradlePlayGitEnvUser'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComMunishPrabhuPGradlePlayGitEnvUser")
    name = "https://github.com/MunishPrabhuP/GradlePlay.git#%env.USER%"
    url = "https://github.com/MunishPrabhuP/GradlePlay.git"
    branch = "%env.USER%"
    branchSpec = ""
    authMethod = password {
        userName = "MunishPrabhuP"
        password = "credentialsJSON:2bffb926-5216-43a3-a30e-e8b9311ba7c3"
    }
}))

