package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComMunishPrabhuPGradlePlayGitRefsHeadsMaster1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComMunishPrabhuPGradlePlayGitRefsHeadsMaster1")
    name = "https://github.com/MunishPrabhuP/GradlePlay.git#refs/heads/master (1)"
    url = "https://github.com/MunishPrabhuP/GradlePlay.git"
    branch = "refs/heads/master"
    branchSpec = "refs/heads/*"
    checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.USE_MIRRORS
}))

